version: "3.9"

services:
  voice-to-srt:
    build: .
    container_name: voice-to-srt
    ports:
      - "7860:7860"
    environment:
      - KMP_DUPLICATE_LIB_OK=TRUE
      - KMP_INIT_AT_FORK=FALSE
      - OMP_NUM_THREADS=1
      - OMP_MAX_ACTIVE_LEVELS=1
      - OMP_THREAD_LIMIT=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
    volumes:
      - whisper-cache:/root/.cache/whisper

volumes:
  whisper-cache:
