@echo off
setlocal

set KMP_DUPLICATE_LIB_OK=TRUE
set KMP_INIT_AT_FORK=FALSE
set OMP_NUM_THREADS=1
set OMP_MAX_ACTIVE_LEVELS=1
set OMP_THREAD_LIMIT=1
set MKL_NUM_THREADS=1
set NUMEXPR_NUM_THREADS=1
set VECLIB_MAXIMUM_THREADS=1

python gui.py

endlocal
